sudo: required
services:
  - docker
before_install:
  - docker build -t xtatanx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xtatanx/react-test npm test

after_success:
  - docker build -t xtatanx/multi-client ./client
  - docker build -t xtatanx/multi-nginx ./nginx
  - docker build -t xtatanx/multi-server ./server
  - docker build -t xtatanx/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xtatanx/multi-client
  - docker push xtatanx/multi-nginx
  - docker push xtatanx/multi-server
  - docker push xtatanx/multi-worker
